### ISSUE TITLE
error: too many requests

### ISSUE THREAD

**Issue by eugenius109** [d4n3436/GTranslate#10]
Hi!
Can you tell me how many requests are allowed?

**Comment by d4n3436** [comment]
Can you provide a stack trace or code that reproduces the error?

**Comment by eugenius109** [comment]
![image](https://github.com/user-attachments/assets/d6b1323f-2a79-406e-9ec5-bc093a9243db)
Hi!
Sorry, I'm not an experienced programmer =)
I attach a screenshot.

I tried to make requests every 10 seconds and only get to make about 20 requests after which an error appears.

Thanks

**Comment by d4n3436** [comment]
If you are not making too many requests, then the issue may be caused by `MicrosoftTranslator`. Currently it only allows to translate up to 1000 characters at a time.
