### ISSUE TITLE
French (Canada) is not working.

### ISSUE THREAD

**Issue by MarcoMedrano** [d4n3436/GTranslate#11]
Hello,  first of all thanks for such a good lib.
I notice **fr-CA** is not working, digging a bit i relized it is using the Bing and Microsoft translators. 
Got these exceptions:

{"JSON deserialization for type 'GTranslate.Models.MicrosoftTranslationResultModel' was missing required properties, including the following: detectedLanguage"}
and
{"JSON deserialization for type 'GTranslate.Models.BingDetectedLanguageModel' was missing required properties, including the following: score"}

Looking up with fiddler, the translation is correctly there, althought I did not find the **detectedLanguage** neither the **score.**

Seems any translation made using the Bing and Microsoft translation are failing.
Tried so far: French (Canada), Chhattisgarhi, Upper Sorbian

**Comment by d4n3436** [comment]
It seems that Bing has changed the response body of their translator. As for the error on `MicrosoftTranslator`, I didn't realize that the `detectedLanguage` field is only present when language autodetection occurs.
