### ISSUE TITLE
AggregateTranslator.TranslateAsync() returns no list of translated texts from the defined Translators.

### ISSUE THREAD

**Issue by abussl** [d4n3436/GTranslate#4]
AggregateTranslator.TranslateAsync() returns no list of translated texts from the defined Translators. 

Detected bug/malfunction: The function returns after the first iteration. 

This should be possible:
```
var backTranslator = new AggregateTranslator(new List<GTranslate.Translators.ITranslator>()
{
    new GoogleTranslator(),
    new MicrosoftTranslator(),
    new YandexTranslator(),
    new BingTranslator()
});

//Expected:
List<ITranslationResult> result = await backTranslator.TranslateAsync(translatedText?.Text, "de");

//Currently:
// Only returns the result of GoogleTranslator in a single instance;
```

Thank you for sharing your work and happy new year :-)

**Comment by d4n3436** [comment]
Hello, that's the intended behavior. `AggregrateTranslator` uses the translation services in the order provided. If one fails, the next translator is used.
