### ISSUE TITLE
Great project but it lacks documentation

### ISSUE THREAD

**Issue by knowpwr** [d4n3436/GTranslate#6]
Hello. First of all, thanks a lot for this great project. It is one of the most understarred projects out there even though it delivers. The problem is that this project lacks documentation. I had to dig deep into the project to find what I want. The example provided is very limited. I suggest you work on the documentation or at least give examples of usage if you do not have the time. Give multiple examples on README page. How to specifically use Google service alone, for example. Give as much examples as you can to cover what the project offers.

Regards and thanks again.

**Comment by d4n3436** [comment]
Hey. The library is fully documented with XML comments. Your IDE should provide information about the methods, classes and objects of the library through the editor and the debugger. You're right about the examples and I will provide more usage examples on the README soon.
